### ISSUE TITLE
Ideas on changes to Pull Request #31 

### ISSUE THREAD

**Issue by jnnkls** [FHA-FB5/FortuneTeller#35]
Unfortunately, I didn't have time for a review of #31. But here are some thoughts: 
* We could give the footer a darker color so that the contrast is more visible. 
* Then we could reduce the copyright text a little bit (e.g. FHA Bereich 5) because on mobile it would otherwise be a bit squeezed. 
* On certain screen sizes (e.g. iPhone 6) I get interesting white/greenish stripes at the lower wave. In addition, the footer slips a bit too high. 
![stripes2](https://user-images.githubusercontent.com/5995845/65469086-6b50d200-de66-11e9-9af8-f8efa7eeb8af.PNG)

* I don't know if you use a custom font but on my browser the text *FortuneTeller* shows as Comic Sans. I would be happy if we could change that 😉. 
* On mobile phones bevor iPhone 6 / Samsung Galaxy 6 the upper part (Anrede) starts squeezing into the header. 

Chears Jani

**Comment by JaniDJ** [comment]
#31

**Comment by KnutZuidema** [comment]
Sounds good. Feel free to create a pull request yourself. The soonest I could work on this would be tomorrow.

**Comment by KnutZuidema** [comment]
Also, I would highly appreciate a fix for the stripes on the waves. Couldn't figure out why it did that. One solution might be to not randomize the wave length and height and just find a value that works.

Regarding the font, I thought I supplied the custom font as a static asset, but maybe that didn't work. You could look into that, it's located at `web/public/fonts`.

**Comment by jnnkls** [comment]
I start looking into it. So the random stripes are a result of the rotation in connection with the height of the footer which is set via view height. The missing font can be solved (at least in my chrome) by deleting ", cursive" in the font-family. I can make a PR tomorrow if you don't already take care of it.

Chears

**Comment by KnutZuidema** [comment]
PR will be appreciated, I'll look into the other things this evening :+1:

**Comment by jnnkls** [comment]
So the only open point would be: 
> On mobile phones bevor iPhone 6 / Samsung Galaxy 6 the upper part (Anrede) starts squeezing into the header.

But I don't have a problem with skipping it.

**Comment by frzifus** [comment]
done
